local screens = require("main.screens")

function init(self)
	gui.set_render_order(1)
end

function on_input(self, action_id, action)
	if action_id == hash("touch") then
		if action.pressed and not action.released then
			if gui.pick_node(gui.get_node("button_close"), action.x, action.y) then
				screens.back()
			elseif gui.pick_node(gui.get_node("button_menu"), action.x, action.y) then
				screens.show("menu")
			end
		end
	end
end
